/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mumu2015
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    public void close(){
        
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonPlaceOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtnCustomerFin = new javax.swing.JButton();
        jBtnBikeFin = new javax.swing.JButton();
        jBtnPartnerFin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jBtnCustomer1 = new javax.swing.JButton();
        jBtnBike1 = new javax.swing.JButton();
        jBtnPartner1 = new javax.swing.JButton();
        jButtonSpecialInfo = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 244, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "PICK A RIDE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 24), new java.awt.Color(204, 0, 0))); // NOI18N

        jButtonPlaceOrder.setBackground(new java.awt.Color(153, 255, 153));
        jButtonPlaceOrder.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButtonPlaceOrder.setText("PLACE AN ORDER");
        jButtonPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlaceOrderActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "FINANCIAL ACTIVITIES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 14), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(649, 71));

        jBtnCustomerFin.setBackground(new java.awt.Color(255, 204, 255));
        jBtnCustomerFin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnCustomerFin.setText("CUSTOMER");
        jBtnCustomerFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustomerFinActionPerformed(evt);
            }
        });

        jBtnBikeFin.setBackground(new java.awt.Color(255, 204, 255));
        jBtnBikeFin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnBikeFin.setText("BIKE");
        jBtnBikeFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBikeFinActionPerformed(evt);
            }
        });

        jBtnPartnerFin.setBackground(new java.awt.Color(255, 204, 255));
        jBtnPartnerFin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnPartnerFin.setText("PARTNER");
        jBtnPartnerFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPartnerFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnCustomerFin)
                .addGap(18, 18, 18)
                .addComponent(jBtnBikeFin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnPartnerFin)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCustomerFin)
                    .addComponent(jBtnBikeFin)
                    .addComponent(jBtnPartnerFin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "REGISTRATION", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 14), new java.awt.Color(153, 0, 0))); // NOI18N

        jBtnCustomer1.setBackground(new java.awt.Color(255, 204, 255));
        jBtnCustomer1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnCustomer1.setText("CUSTOMER");
        jBtnCustomer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustomer1ActionPerformed(evt);
            }
        });

        jBtnBike1.setBackground(new java.awt.Color(255, 204, 255));
        jBtnBike1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnBike1.setText("BIKE");
        jBtnBike1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBike1ActionPerformed(evt);
            }
        });

        jBtnPartner1.setBackground(new java.awt.Color(255, 204, 255));
        jBtnPartner1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtnPartner1.setText("PARTNER");
        jBtnPartner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPartner1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnCustomer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jBtnBike1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnPartner1)
                .addGap(332, 332, 332))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCustomer1)
                    .addComponent(jBtnBike1)
                    .addComponent(jBtnPartner1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonSpecialInfo.setBackground(new java.awt.Color(255, 204, 102));
        jButtonSpecialInfo.setFont(new java.awt.Font("Cambria", 1, 11)); // NOI18N
        jButtonSpecialInfo.setText("SPECIAL INFORMATIONS");
        jButtonSpecialInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpecialInfoActionPerformed(evt);
            }
        });

        jButtonExit.setBackground(new java.awt.Color(51, 153, 255));
        jButtonExit.setFont(new java.awt.Font("Cambria", 1, 11)); // NOI18N
        jButtonExit.setText("EXIT");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButtonPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButtonSpecialInfo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jButtonExit)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPlaceOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButtonSpecialInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExit)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(215, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(763, 451));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCustomer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustomer1ActionPerformed
        // TODO add your handling code here:
        close();
        Customer customer = new Customer() ;
        customer.setVisible(true);
    }//GEN-LAST:event_jBtnCustomer1ActionPerformed

    private void jBtnBike1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBike1ActionPerformed
        // TODO add your handling code here:
         close();
        Bike bike = new Bike() ;
        bike.setVisible(true);
    }//GEN-LAST:event_jBtnBike1ActionPerformed

    private void jBtnPartner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPartner1ActionPerformed
        // TODO add your handling code here:
        close();
        Partner partner = new Partner() ;
        partner.setVisible(true);
    }//GEN-LAST:event_jBtnPartner1ActionPerformed

    private void jBtnCustomerFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustomerFinActionPerformed
        // TODO add your handling code here:
        close();
        MainFinance mainfinance = new MainFinance() ;
        mainfinance.setVisible(true);
    }//GEN-LAST:event_jBtnCustomerFinActionPerformed

    private void jBtnBikeFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBikeFinActionPerformed
        // TODO add your handling code here:

        close();
        BikeFinance bikefinance = new BikeFinance() ;
        bikefinance.setVisible(true);
    }//GEN-LAST:event_jBtnBikeFinActionPerformed

    private void jBtnPartnerFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPartnerFinActionPerformed
        // TODO add your handling code here:
        close();
        PartnerFinance partnerfinance = new PartnerFinance() ;
        partnerfinance.setVisible(true);
    }//GEN-LAST:event_jBtnPartnerFinActionPerformed

    private void jButtonPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlaceOrderActionPerformed
        // TODO add your handling code here:
        
        
        close();
        OF of = new OF() ;
        of.setVisible(true);
    }//GEN-LAST:event_jButtonPlaceOrderActionPerformed

    private void jButtonSpecialInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpecialInfoActionPerformed
        // TODO add your handling code here:
        close();
        Information info = new Information() ;
        info.setVisible(true);
    }//GEN-LAST:event_jButtonSpecialInfoActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        
        JFrame frame = new JFrame ("EXIT");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to EXIT","Exit",
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBike1;
    private javax.swing.JButton jBtnBikeFin;
    private javax.swing.JButton jBtnCustomer1;
    private javax.swing.JButton jBtnCustomerFin;
    private javax.swing.JButton jBtnPartner1;
    private javax.swing.JButton jBtnPartnerFin;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPlaceOrder;
    private javax.swing.JButton jButtonSpecialInfo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
